### PR TITLE
Rewrites eventbus and updates documentation

### PR DESCRIPTION
**Pull request by michielpapenhove**
Exactly what the PR name says ;)

(added a little test example in code too which I think I need to remove before merging)

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Wouldn't the EventBus and the Event like some tests? :D

**Comment by ramondelafuente** [comment]
I'm looking into the tests, but I also came across this: `https://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%20language%20overview/accessors.html`

Accessors might improve the code needed to find values in the list.

Finally, we might have a problem with this datastructure; I think setting the same key will overwrite the value at that position...

**Comment by michielpapenhove** [comment]
> Finally, we might have a problem with this datastructure; I think setting the same key will overwrite the value at that position...

Do you have an example of this? In the example tests that are still in the code for this PR I use a subscribe to the HitBulletEvent twice and that seems to be working fine. As long as we're adding subscribers through the subscribe method, it shouldn't be possible to use the same key, I think. But that might not be what you're talking about...

**Comment by ramondelafuente** [comment]
@michielpapenhove Sorry, outdated info. Multiple listeners works - I have added the test to prove it :D

**Comment by michielpapenhove** [comment]
> @michielpapenhove Sorry, outdated info. Multiple listeners works - I have added the test to prove it :D

Nice :D Can I merge the branch then?

**Pull request merged**
