### PR TITLE
Moar sounds

### LINKED ISSUE #29: Solve continuous looping when the game is lost.
Currently, when the game is "lost", a global variable is set that skips certain actions. But the game loop is still running and "skipping" due to if-statements in the code. 

We should think more in events, and make sure we fire an event for "game end" instead of adding if-statements that check the global variable.

In the "moar sounds" PR, the player object is destroyed on loss to prevent contuous collision detection.

### PR DESCRIPTION
**Pull request by ramondelafuente**
This PR adds a loss sound when the game is over. I decided to destroy the player once the collision is detected, because otherwise the game-loop will continue to run the collision event code all the time. Due to the fact that the "R to restart" button is part of the player, this no longer works... which is why I moved the control keys over to the game controller object (see PR #31).

There is also a win sound - but we don't have a place to put that yet 🤔

### CODE REVIEW

**Review by michielpapenhove — APPROVED** [review]

**Comment by verschoof** [comment]
Haha we rock with the sound effects 😂 👍 NICE

**Comment by verschoof** [comment]
It still feels weird we have to remove the player because because thats the "base" of the game... if you have for example 2 players we will have double steps right... so I think we have to fix this too?

**Comment by ramondelafuente** [comment]
I don't think the player should be the "base of the game". The responsibility of the player is to be the player, and handle all things regarding the player. Responsibilities regarding game-flow should be elsewhere, like the game controller object.

Like you said, if we have two players later, who's responsibility would it be to be the "base of the game"?

**Comment by ramondelafuente** [comment]
The game controller can also handle things like pause/start and win/loss scenario's.

**Pull request merged**
