### PR TITLE
Adds mp3 files that can be used for the soundtrack

### LINKED ISSUE #16: Add a kickass @mitchett original soundtrack!

### PR DESCRIPTION
**Pull request by michielpapenhove**

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Neat! Kickass music is exactly what we need now!

heavy metal

Starting the game takes ages now though, I think "compiling" the MP3's is done? Not sure if that's the correct terminology... is there anything we can do about that? Also, the git repo took a 100MB hit, which we might also be able to avoid... (not sure how)?

**Comment by michielpapenhove** [comment]
Hm, it only It took a few seconds extra on my computer to start the game. The original files are in a 320kbps bitrate which results in rather large files. That's why I told Gamemaker to use 192 which should take the size down but as far as I can tell, it didn't transcode them. I'm gonna try and fiddle with some options and use "streamed" instead of "not streamed".

**Comment by ramondelafuente** [comment]
This gave a few xtra seconds in the first run, and almost no delay for the subsequent run. Noice!

**Comment by michielpapenhove** [comment]
I don't really get what Gamemaker is doing... The tracks are now set to "compressed" and "streamed" and I see the conversion happening when I run the game. That's a one time thing but then the files don't change at all, so I guess Gamemaker is rendering/transcoding them to a different place. So the 100MB size hit still stands. ~But does the game quicker for you too once Gamemaker has converted the tracks~? If so I think transcoding the originals to 192 kbps instead of 320 will result in a much smaller size hit.

**Comment by michielpapenhove** [comment]
Good to hear it works :) Still don't get where Gamemaker is transcoding the files too however ;) I'll convert the originals to 192 kpbs ASAP to reduce the size hit.

**Comment by ramondelafuente** [comment]
I think it might be compiling into the binary... I get a file called `~/GameMakerStudio2/GMS2MAC/Space_Invaders/YoYoRunner.app` when I run the game.

**Comment by verschoof** [comment]
Nice! we can merge this right? Later on we can see how to make it faster?

**Comment by ramondelafuente** [comment]
Removing large files from a repo 's history is shitty work, it might be prudent to hold off on this one untill we reduced the size a little.

**Comment by verschoof** [comment]
Why we have to remove it from the history?

**Comment by ramondelafuente** [comment]
Git init
Git add 100MB
Git remove 90MB

Your repo is still 100MB (git clone downloads 100MB)

If we change the size _before_ merging the 100MB never goes to the history.

**Comment by ramondelafuente** [comment]
So I mean we wait for this comment from @michielpapenhove:

> I'll convert the originals to 192 kpbs ASAP to reduce the size hit.

**Comment by michielpapenhove** [comment]
I converted the files to 192kbps and now they add up to about 66 Mb... Still a bit much, perhaps? Maybe we should just pick a few tracks instead of using all of them?

**Pull request merged**
