### PR TITLE
Adds simple eventbus

### PR DESCRIPTION
**Pull request by michielpapenhove**
I tried to add a really basic EventBus functionality to the game so the code gets a bit more managable. It turns out that Gamemaker 2 has a thing called "structs" which makes it possible to work a bit more object oriented. As an example of how it works, I added a bulletHit event which is emitted by the Dot object as soon as it collides with an alien. The main game controller subscribes to this event and when it's triggered shows the id of the alien hit and how many points should be added to the score.

I also used ds_lists (just discovered those today also) instead of arrays because they are a lot easier to manage.

(Note: If we're going to use this, I will first remove the example code and just leave the EventBus script before merging)

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Did you take a look at https://github.com/gm-core/event-horizon ?
It's part of the same library as GMTest

**Comment by ramondelafuente** [comment]
I'm loving the idea of adding an event-bus by the way! ❤️ 
And also digging into the available datatypes 👍 

I still think we should lay down some really basic rules around what we think is an acceptable scope for variables and functions. Maybe a little mob sessions would do it :-)

**Comment by michielpapenhove** [comment]
> Did you take a look at https://github.com/gm-core/event-horizon ?
> It's part of the same library as GMTest

Ah, very nice :) And no, I didn't have a look at that one but it looks like I re-invented the wheel :P Theirs is probably a bit more refined/sophisticated so let's go for that one then.

**Comment by michielpapenhove** [comment]
> > Did you take a look at https://github.com/gm-core/event-horizon ?
> > It's part of the same library as GMTest
> 
> Ah, very nice :) And no, I didn't have a look at that one but it looks like I re-invented the wheel :P Theirs is probably a bit more refined/sophisticated so let's go for that one then.

Agree :)

**Comment by ramondelafuente** [comment]
It turns out, there is _nothing_ more refined or sophisticated about the event-horizon package - it does exactly the same. You did not re-invent the wheel, you implemented a strategy/pattern in a completely new language. Rock on!

Let's go with yours. Approved AF!

**Comment by ramondelafuente** [comment]
Oh, and sorry - I think I messed up my chain of branches :-/
But I think you said you wanted to fix some things before merging, right?

**Review by ramondelafuente — APPROVED** [review]
N-O-I-C-E

**Comment by michielpapenhove** [comment]
> Oh, and sorry - I think I messed up my chain of branches :-/
> But I think you said you wanted to fix some things before merging, right?

Yes, the example code is not needed, just the EventBus script. Which will probably also fix the conflicts as I used the Dot object to add the example code to.

**Comment by michielpapenhove** [comment]
Nope, that did not fix the conflicts :P I'm gonna try the Github web editor to fix this.

**Comment by michielpapenhove** [comment]
I think this should do it. If not, apologies for breaking stuff.

**Comment by verschoof** [comment]
Noice!

**Pull request merged**
